// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABSe3j48fFQpMUJFgal0pyNHwnAiAlI_A',
    appId: '1:1079834747063:web:395efdfe4ee95140bdad32',
    messagingSenderId: '1079834747063',
    projectId: 'jaes-51995',
    authDomain: 'jaes-51995.firebaseapp.com',
    storageBucket: 'jaes-51995.firebasestorage.app',
    measurementId: 'G-2EHF1SHWS7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb0_3Wzj2xhhlfxbLSGwrTxdVQDEzXq1k',
    appId: '1:1079834747063:ios:5ea02cf508259fd5bdad32',
    messagingSenderId: '1079834747063',
    projectId: 'jaes-51995',
    storageBucket: 'jaes-51995.firebasestorage.app',
    androidClientId: '1079834747063-s8s8bdpbueggnv6bkttd5mfa1fhgeqes.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFYewPnExVsb6p--iU7umXPlS2PO85ghY',
    appId: '1:1079834747063:android:fe1b6de45c8f7b7dbdad32',
    messagingSenderId: '1079834747063',
    projectId: 'jaes-51995',
    storageBucket: 'jaes-51995.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb0_3Wzj2xhhlfxbLSGwrTxdVQDEzXq1k',
    appId: '1:1079834747063:ios:5ea02cf508259fd5bdad32',
    messagingSenderId: '1079834747063',
    projectId: 'jaes-51995',
    storageBucket: 'jaes-51995.firebasestorage.app',
    androidClientId: '1079834747063-s8s8bdpbueggnv6bkttd5mfa1fhgeqes.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABSe3j48fFQpMUJFgal0pyNHwnAiAlI_A',
    appId: '1:1079834747063:web:395efdfe4ee95140bdad32',
    messagingSenderId: '1079834747063',
    projectId: 'jaes-51995',
    authDomain: 'jaes-51995.firebaseapp.com',
    storageBucket: 'jaes-51995.firebasestorage.app',
    measurementId: 'G-2EHF1SHWS7',
  );

}